# Generated by Django 3.0.2 on 2020-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0002_auto_20200125_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=30),
        ),
    ]
