# Generated by Django 3.0.2 on 2020-02-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0003_auto_20200204_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koyla',
            name='la',
            field=models.CharField(max_length=100),
        ),
    ]
